--Dropping tables, views, and stored procedures so code can be ran repeatedly and everything is recreated each time
DROP TABLE IF EXISTS HEISMAN_WINNER
DROP TABLE IF EXISTS ACC_SEASON
DROP TABLE IF EXISTS ACC_SCHOOL
DROP VIEW IF EXISTS HEISMAN_VIEW
DROP VIEW IF EXISTS ACC_SEASONS_VIEW
DROP VIEW IF EXISTS ACC_SCHOOLS_VIEW
DROP PROCEDURE IF EXISTS ENTER_HEISMAN
DROP PROCEDURE IF EXISTS ENTER_SEASON
DROP PROCEDURE IF EXISTS HEISMAN_WINNER_ACC_SCHOOL_ID
DROP PROCEDURE IF EXISTS HEISMAN_WINNER_ACC_SEASON_ID

--Creating ACC_SCHOOL table
CREATE TABLE ACC_SCHOOL(
	ACC_SCHOOL_ID INT IDENTITY PRIMARY KEY,
	SCHOOL_NAME VARCHAR(50) UNIQUE NOT NULL,
	SCHOOL_CITY VARCHAR(50) NOT NULL,
	SCHOOL_STATE VARCHAR(2) NOT NULL,
	GRADUATION_RATE DECIMAL(4,3) NOT NULL)

--Creating ACC_SEASON table
CREATE TABLE ACC_SEASON(
	ACC_SEASON_ID INT IDENTITY PRIMARY KEY,
	ACC_SCHOOL_ID INT NOT NULL,
	SEASON_YEAR DATE NOT NULL,
	WINS INT NOT NULL,
	LOSSES INT NOT NULL,
	TIES INT,
	ACC_CHAMPION BIT NOT NULL,
	CONSTRAINT FK1_ACC_SEASON
		FOREIGN KEY (ACC_SCHOOL_ID) REFERENCES ACC_SCHOOL(ACC_SCHOOL_ID),
	CONSTRAINT U1_ACC_SEASON
		UNIQUE (ACC_SCHOOL_ID, SEASON_YEAR))

--Creating HEISMAN_WINNER table
CREATE TABLE HEISMAN_WINNER(
	HEISMAN_WINNER_ID INT IDENTITY PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	ACC_SCHOOL_ID INT,
	ACC_SEASON_ID INT,
	HEISMAN_SCHOOL_NAME VARCHAR(50) NOT NULL,
	HEISMAN_YEAR DATE NOT NULL,
	CLASS VARCHAR(10) NOT NULL,
	REDSHIRT BIT NOT NULL,
	POSITION VARCHAR(10) NOT NULL,
	CONSTRAINT FK1_HEISMAN_WINNER
		FOREIGN KEY (ACC_SCHOOL_ID) REFERENCES ACC_SCHOOL(ACC_SCHOOL_ID),
	CONSTRAINT FK2_HEISMAN_WINNER
		FOREIGN KEY (ACC_SEASON_ID) REFERENCES ACC_SEASON(ACC_SEASON_ID))

--INSERTING data into ACC_SCHOOL
INSERT INTO ACC_SCHOOL (SCHOOL_NAME, SCHOOL_CITY, SCHOOL_STATE, GRADUATION_RATE) VALUES
	('Clemson University','Clemson','SC',0.828),
	('Duke University','Durham','NC',0.956),
	('University of Maryland','College Park','MD',0.854),
	('University of North Carolina','Chapel Hill','NC',0.893),
	('North Carolina State University','Raleigh','NC',0.808),
	('University of South Carolina','Columbia','SC',0.78),
	('University of Virginia','Charlottesville','VA',0.943),
	('Wake Forest University','Winston-Salem','NC',0.883),
	('Georgia Institute of Technology','Atlanta','GA',0.872),
	('Florida State University','Tallahassee','FL',0.825),
	('University of Miami','Coral Gables','FL',0.816),
	('Virginia Tech','Blacksburg','VA',0.835),
	('Boston College','Chestnut Hill','MA',0.919),
	('University of Notre Dame','Notre Dame','IN',0.969),
	('University of Pittsburgh','Pittsburgh','PA',0.825),
	('Syracuse University','Syracuse','NY',0.826),
	('University of Louisville','Louisville','KY',0.559)

--Checking the results
SELECT * FROM ACC_SCHOOL

--INSERTING into HEISMAN_WINNER table. WILL ENTER ACC_SCHOOL_ID and ACC_SEASON_ID LATER
INSERT INTO HEISMAN_WINNER (HEISMAN_YEAR,NAME,HEISMAN_SCHOOL_NAME,POSITION,CLASS,REDSHIRT) VALUES
('1935','Jay Berwanger','Chicago','HB','Senior',0),
('1936','Larry Kelley','Yale','End','Senior',0),
('1937','Clint Frank','Yale','HB','Senior',0),
('1938','Davey O''Brien','TCU','QB','Senior',0),
('1939','Nile Kinnick','Iowa','HB/QB','Senior',0),
('1940','Tom Harmon','Michigan','HB','Senior',0),
('1941','Bruce Smith','Minnesota','HB','Senior',0),
('1942','Frank Sinkwich','Georgia','HB','Senior',0),
('1943','Angelo Bertelli','University of Notre Dame','QB','Senior',0),
('1944','Les Horvath','Ohio State','HB/QB','Senior',0),
('1945','Doc Blanchard','Army','FB','Junior',0),
('1946','Glenn Davis','Army','HB','Senior',0),
('1947','Johnny Lujack','University of Notre Dame','QB','Senior',0),
('1948','Doak Walker','SMU','HB','Junior',0),
('1949','Leon Hart','University of Notre Dame','End','Senior',0),
('1950','Vic Janowicz','Ohio State','HB/P','Junior',0),
('1951','Dick Kazmaier','Princeton','HB','Senior',0),
('1952','Billy Vessels','Oklahoma','HB','Senior',0),
('1953','Johnny Lattner','University of Notre Dame','HB','Senior',0),
('1954','Alan Ameche','Wisconsin','FB','Senior',0),
('1955','Howard Cassady','Ohio State','HB','Senior',0),
('1956','Paul Hornung','University of Notre Dame','QB','Senior',0),
('1957','John David Crow','Texas A&M','HB','Senior',0),
('1958','Pete Dawkins','Army','HB','Senior',0),
('1959','Billy Cannon','LSU','HB','Senior',0),
('1960','Joe Bellino','Navy','HB','Senior',0),
('1961','Ernie Davis','Syracuse University','HB/LB/FB','Senior',0),
('1962','Terry Baker','Oregon State','QB','Senior',0),
('1963','Roger Staubach','Navy','QB','Junior',0),
('1964','John Huarte','University of Notre Dame','QB','Senior',0),
('1965','Mike Garrett','USC','HB','Senior',0),
('1966','Steve Spurrier','Florida','QB','Senior',0),
('1967','Gary Beban','UCLA','QB','Senior',0),
('1968','O. J. Simpson','USC','HB','Senior',0),
('1969','Steve Owens','Oklahoma','FB','Senior',0),
('1970','Jim Plunkett','Stanford','QB','Senior',1),
('1971','Pat Sullivan','Auburn','QB','Senior',0),
('1972','Johnny Rodgers','Nebraska','WR/RB','Senior',0),
('1973','John Cappelletti','Penn State','RB','Senior',0),
('1974','Archie Griffin','Ohio State','RB','Junior',0),
('1975','Archie Griffin','Ohio State','RB','Senior',0),
('1976','Tony Dorsett','University of Pittsburgh','RB','Senior',0),
('1977','Earl Campbell','Texas','RB','Senior',0),
('1978','Billy Sims','Oklahoma','RB','Junior',1),
('1979','Charles White','USC','RB','Senior',0),
('1980','George Rogers','University of South Carolina','RB','Senior',0),
('1981','Marcus Allen','USC','RB','Senior',0),
('1982','Herschel Walker','Georgia','RB','Junior',0),
('1983','Mike Rozier','Nebraska','RB','Senior',0),
('1984','Doug Flutie','Boston College','QB','Senior',0),
('1985','Bo Jackson','Auburn','RB','Senior',0),
('1986','Vinny Testaverde','University of Miami','QB','Senior',1),
('1987','Tim Brown','University of Notre Dame','WR','Senior',0),
('1988','Barry Sanders','Oklahoma State','RB','Junior',0),
('1989','Andre Ware','Houston','QB','Junior',0),
('1990','Ty Detmer','BYU','QB','Junior',1),
('1991','Desmond Howard','Michigan','WR/PR','Junior',1),
('1992','Gino Torretta','University of Miami','QB','Senior',1),
('1993','Charlie Ward','Florida State University','QB','Senior',1),
('1994','Rashaan Salaam','Colorado','RB','Junior',0),
('1995','Eddie George','Ohio State','RB','Senior',0),
('1996','Danny Wuerffel','Florida','QB','Senior',1),
('1997','Charles Woodson','Michigan','CB','Junior',0),
('1998','Ricky Williams','Texas','RB','Senior',0),
('1999','Ron Dayne','Wisconsin','RB','Senior',0),
('2000','Chris Weinke','Florida State University','QB','Senior',0),
('2001','Eric Crouch','Nebraska','QB / WR','Senior',1),
('2002','Carson Palmer','USC','QB','Senior',1),
('2003','Jason White','Oklahoma','QB','Senior',1),
('2004','Matt Leinart','USC','QB','Junior',1),
('2006','Troy Smith','Ohio State','QB','Senior',1),
('2007','Tim Tebow','Florida','QB','Sophomore',0),
('2008','Sam Bradford','Oklahoma','QB','Sophomore',1),
('2009','Mark Ingram Jr.','Alabama','RB','Sophomore',0),
('2010','Cam Newton','Auburn','QB','Junior',1),
('2011','Robert Griffin III','Baylor','QB','Junior',1),
('2012','Johnny Manziel','Texas A&M','QB','Freshman',1),
('2013','Jameis Winston','Florida State University','QB','Freshman',1),
('2014','Marcus Mariota','Oregon','QB','Junior',1),
('2015','Derrick Henry','Alabama','RB','Junior',0),
('2016','Lamar Jackson','University of Louisville','QB','Sophomore',0),
('2017','Baker Mayfield','Oklahoma','QB','Senior',1),
('2018','Kyler Murray','Oklahoma','QB','Junior',1),
('2019','Joe Burrow','LSU','QB','Senior',1),
('2020','DeVonta Smith','Alabama','WR','Senior',0),
('2021','Bryce Young','Alabama','QB','Sophomore',0)

--Procedure to populate ACC_SCHOOL_ID in HEISMAN_WINNER
GO
CREATE OR ALTER PROCEDURE HEISMAN_WINNER_ACC_SCHOOL_ID AS
BEGIN
	DECLARE @loop INT = 1
    DECLARE @loopend INT
	DECLARE @ACC_SCHOOL_ID INT
	DECLARE @HEISMAN_SCHOOL_NAME VARCHAR(50)
	SELECT @loopend = COUNT(*) FROM HEISMAN_WINNER
	WHILE @loop <= @loopend
	BEGIN
		SELECT 
			@ACC_SCHOOL_ID = ACCSCH.ACC_SCHOOL_ID,
			@HEISMAN_SCHOOL_NAME = HWIN.HEISMAN_SCHOOL_NAME
		FROM 
			ACC_SCHOOL ACCSCH
		INNER JOIN
			HEISMAN_WINNER HWIN
				ON ACCSCH.SCHOOL_NAME = HWIN.HEISMAN_SCHOOL_NAME
				AND HWIN.ACC_SCHOOL_ID IS NULL
		UPDATE HEISMAN_WINNER SET ACC_SCHOOL_ID = @ACC_SCHOOL_ID WHERE HEISMAN_SCHOOL_NAME = @HEISMAN_SCHOOL_NAME
		SELECT @loop = @loop + 1
	END
END
GO

--Implementing the procedure HEISMAN_WINNER_ACC_SCHOOL_ID
EXEC HEISMAN_WINNER_ACC_SCHOOL_ID

--Checking the results
SELECT * FROM HEISMAN_WINNER

--Inserting into ACC_SEASON table
INSERT INTO ACC_SEASON (ACC_SCHOOL_ID,SEASON_YEAR,WINS,LOSSES,TIES,ACC_CHAMPION) VALUES
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2021',10,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2020',10,2,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2019',14,1,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2018',15,0,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2017',12,2,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2016',14,1,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2015',14,1,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2014',10,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2013',11,2,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2012',11,2,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2011',10,4,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2010',6,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2009',9,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2008',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2007',9,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2006',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2005',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2004',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2003',9,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2002',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2001',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'2000',9,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1999',6,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1998',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1997',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1996',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1995',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1994',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1993',9,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1992',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1991',9,2,1,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1990',10,2,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1989',10,2,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1988',10,2,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1987',10,2,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1986',8,2,2,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1985',6,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1984',7,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1983',9,1,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1982',9,1,1,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1981',12,0,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1980',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1979',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1978',11,1,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1977',8,3,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1976',3,6,2,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1975',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1974',7,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1973',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1972',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1971',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1970',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1969',4,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1968',4,5,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1967',6,4,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1966',6,4,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1965',5,5,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1964',3,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1963',5,4,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1962',6,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1961',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1960',6,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1959',9,2,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1958',8,3,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1957',7,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1956',7,2,2,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1955',7,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1954',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Clemson University'),'1953',3,5,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2021',3,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2020',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2019',5,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2018',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2017',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2016',4,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2015',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2014',9,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2013',10,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2012',6,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2011',3,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2010',3,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2009',5,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2008',4,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2007',1,11,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2006',0,12,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2005',1,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2004',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2003',4,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2002',2,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2001',0,11,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'2000',0,11,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1999',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1998',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1997',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1996',0,11,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1995',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1994',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1993',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1992',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1991',4,6,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1990',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1989',8,4,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1988',7,3,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1987',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1986',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1985',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1984',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1983',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1982',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1981',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1980',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1979',2,8,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1978',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1977',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1976',5,5,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1975',4,5,2,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1974',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1973',2,8,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1972',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1971',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1970',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1969',3,6,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1968',4,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1967',4,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1966',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1965',6,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1964',4,5,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1963',5,4,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1962',8,2,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1961',7,3,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1960',8,3,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1959',4,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1958',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1957',6,3,2,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1956',5,4,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1955',7,2,1,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1954',8,2,1,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Duke University'),'1953',7,2,1,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'2013',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'2012',4,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'2011',2,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'2010',9,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'2009',2,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'2008',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'2007',6,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'2006',9,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'2005',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'2004',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'2003',10,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'2002',11,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'2001',10,2,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'2000',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1999',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1998',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1997',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1996',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1995',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1994',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1993',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1992',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1991',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1990',6,5,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1989',3,7,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1988',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1987',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1986',5,5,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1985',9,3,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1984',9,3,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1983',8,4,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1982',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1981',4,6,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1980',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1979',7,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1978',9,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1977',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1976',11,1,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1975',9,2,1,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1974',8,4,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1973',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1972',5,5,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1971',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1970',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1969',3,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1968',2,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1967',0,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1966',4,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1965',4,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1964',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1963',3,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1962',6,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1961',7,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1960',6,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1959',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1958',4,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1957',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1956',2,7,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1955',10,1,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1954',7,2,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Maryland'),'1953',10,1,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2021',6,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2020',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2019',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2018',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2017',3,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2016',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2015',11,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2014',6,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2013',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2012',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2011',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2010',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2009',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2008',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2007',4,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2006',3,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2005',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2004',6,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2003',2,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2002',3,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2001',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'2000',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1999',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1998',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1997',11,1,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1996',10,2,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1995',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1994',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1993',10,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1992',9,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1991',7,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1990',6,4,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1989',1,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1988',1,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1987',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1986',7,4,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1985',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1984',5,5,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1983',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1982',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1981',10,2,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1980',11,1,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1979',8,3,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1978',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1977',8,3,1,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1976',9,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1975',3,7,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1974',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1973',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1972',11,1,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1971',9,3,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1970',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1969',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1968',3,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1967',2,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1966',2,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1965',4,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1964',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1963',9,2,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1962',3,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1961',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1960',3,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1959',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1958',6,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1957',6,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1956',2,7,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1955',3,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1954',4,5,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of North Carolina'),'1953',4,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2021',9,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2020',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2019',4,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2018',9,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2017',9,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2016',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2015',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2014',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2013',3,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2012',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2011',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2010',9,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2009',5,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2008',6,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2007',5,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2006',3,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2005',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2004',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2003',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2002',11,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2001',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'2000',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1999',6,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1998',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1997',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1996',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1995',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1994',9,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1993',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1992',9,3,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1991',9,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1990',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1989',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1988',8,3,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1987',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1986',8,3,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1985',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1984',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1983',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1982',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1981',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1980',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1979',7,4,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1978',9,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1977',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1976',3,7,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1975',7,4,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1974',9,2,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1973',9,3,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1972',8,3,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1971',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1970',3,7,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1969',3,6,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1968',6,4,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1967',9,2,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1966',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1965',6,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1964',5,5,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1963',8,3,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1962',3,6,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1961',4,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1960',6,3,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1959',1,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1958',2,7,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1957',7,1,2,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1956',3,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1955',4,5,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1954',2,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'North Carolina State University'),'1953',1,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of South Carolina'),'1970',4,6,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of South Carolina'),'1969',7,4,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of South Carolina'),'1968',4,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of South Carolina'),'1967',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of South Carolina'),'1966',1,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of South Carolina'),'1965',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of South Carolina'),'1964',3,5,2,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of South Carolina'),'1963',1,8,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of South Carolina'),'1962',4,5,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of South Carolina'),'1961',4,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of South Carolina'),'1960',3,6,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of South Carolina'),'1959',6,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of South Carolina'),'1958',7,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of South Carolina'),'1957',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of South Carolina'),'1956',7,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of South Carolina'),'1955',3,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of South Carolina'),'1954',6,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of South Carolina'),'1953',7,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2021',6,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2020',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2019',9,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2018',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2017',6,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2016',2,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2015',4,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2014',5,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2013',2,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2012',4,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2011',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2010',4,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2009',3,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2008',5,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2007',9,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2006',5,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2005',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2004',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2003',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2002',9,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2001',5,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'2000',6,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1999',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1998',9,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1997',7,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1996',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1995',9,4,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1994',9,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1993',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1992',7,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1991',8,3,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1990',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1989',10,3,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1988',7,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1987',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1986',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1985',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1984',8,2,2,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1983',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1982',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1981',1,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1980',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1979',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1978',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1977',1,9,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1976',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1975',1,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1974',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1973',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1972',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1971',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1970',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1969',3,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1968',7,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1967',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1966',4,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1965',4,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1964',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1963',2,7,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1962',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1961',4,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1960',0,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1959',0,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1958',1,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1957',3,6,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1956',3,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1955',1,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Virginia'),'1954',3,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2021',11,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2020',4,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2019',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2018',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2017',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2016',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2015',3,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2014',3,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2013',4,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2012',5,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2011',6,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2010',3,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2009',5,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2008',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2007',9,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2006',11,3,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2005',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2004',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2003',5,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2002',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2001',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'2000',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1999',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1998',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1997',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1996',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1995',1,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1994',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1993',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1992',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1991',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1990',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1989',2,8,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1988',6,4,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1987',7,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1986',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1985',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1984',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1983',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1982',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1981',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1980',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1979',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1978',1,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1977',1,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1976',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1975',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1974',1,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1973',1,9,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1972',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1971',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1970',6,5,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1969',3,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1968',2,7,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1967',4,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1966',3,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1965',3,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1964',5,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1963',1,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1962',0,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1961',4,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1960',2,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1959',6,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1958',3,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1957',0,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1956',2,5,3,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1955',5,4,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1954',2,7,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Wake Forest University'),'1953',3,6,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2021',3,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2020',3,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2019',3,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2018',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2017',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2016',9,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2015',3,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2014',11,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2013',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2012',7,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2011',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2010',6,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2009',11,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2008',9,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2007',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2006',9,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2005',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2004',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2003',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2002',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2001',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'2000',9,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'1999',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'1998',10,2,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'1997',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'1996',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'1995',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'1994',1,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'1993',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'1992',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'1991',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'1990',11,0,1,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'1989',7,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'1988',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'1987',2,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'1986',5,5,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'1985',9,2,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'1984',6,4,1,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Georgia Institute of Technology'),'1983',3,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2021',5,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2020',3,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2019',6,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2018',5,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2017',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2016',10,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2015',10,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2014',13,1,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2013',14,0,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2012',12,2,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2011',9,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2010',10,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2009',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2008',9,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2007',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2006',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2005',8,5,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2004',9,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2003',10,3,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2002',9,5,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2001',8,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'2000',11,2,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'1999',12,0,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'1998',11,2,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'1997',11,1,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'1996',11,1,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'1995',10,2,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'1994',10,1,1,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'1993',12,1,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Florida State University'),'1992',11,1,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Miami'),'2021',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Miami'),'2020',8,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Miami'),'2019',6,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Miami'),'2018',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Miami'),'2017',10,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Miami'),'2016',9,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Miami'),'2015',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Miami'),'2014',6,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Miami'),'2013',9,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Miami'),'2012',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Miami'),'2011',6,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Miami'),'2010',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Miami'),'2009',9,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Miami'),'2008',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Miami'),'2007',5,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Miami'),'2006',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Miami'),'2005',9,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Miami'),'2004',9,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Virginia Tech'),'2021',6,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Virginia Tech'),'2020',5,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Virginia Tech'),'2019',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Virginia Tech'),'2018',6,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Virginia Tech'),'2017',9,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Virginia Tech'),'2016',10,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Virginia Tech'),'2015',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Virginia Tech'),'2014',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Virginia Tech'),'2013',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Virginia Tech'),'2012',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Virginia Tech'),'2011',11,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Virginia Tech'),'2010',11,3,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Virginia Tech'),'2009',10,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Virginia Tech'),'2008',10,4,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Virginia Tech'),'2007',11,3,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Virginia Tech'),'2006',10,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Virginia Tech'),'2005',11,2,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Virginia Tech'),'2004',10,3,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Boston College'),'2021',6,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Boston College'),'2020',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Boston College'),'2019',6,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Boston College'),'2018',7,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Boston College'),'2017',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Boston College'),'2016',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Boston College'),'2015',3,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Boston College'),'2014',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Boston College'),'2013',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Boston College'),'2012',2,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Boston College'),'2011',4,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Boston College'),'2010',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Boston College'),'2009',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Boston College'),'2008',9,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Boston College'),'2007',11,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Boston College'),'2006',10,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Boston College'),'2005',9,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Notre Dame'),'2020',10,2,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Pittsburgh'),'2021',11,3,NULL,1),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Pittsburgh'),'2020',6,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Pittsburgh'),'2019',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Pittsburgh'),'2018',7,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Pittsburgh'),'2017',5,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Pittsburgh'),'2016',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Pittsburgh'),'2015',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Pittsburgh'),'2014',6,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Pittsburgh'),'2013',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Syracuse University'),'2021',5,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Syracuse University'),'2020',1,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Syracuse University'),'2019',5,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Syracuse University'),'2018',10,3,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Syracuse University'),'2017',4,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Syracuse University'),'2016',4,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Syracuse University'),'2015',4,8,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Syracuse University'),'2014',3,9,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Syracuse University'),'2013',7,6,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Louisville'),'2021',6,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Louisville'),'2020',4,7,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Louisville'),'2019',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Louisville'),'2018',2,10,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Louisville'),'2017',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Louisville'),'2016',9,4,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Louisville'),'2015',8,5,NULL,0),
((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'University of Louisville'),'2014',9,4,NULL,0)



--Check out the results
SELECT * FROM ACC_SEASON

--Procedure to populate ACC_SEASON_ID in HEISMAN_WINNER
GO
CREATE OR ALTER PROCEDURE HEISMAN_WINNER_ACC_SEASON_ID AS
BEGIN
	DECLARE @loop INT = 1
    DECLARE @loopend INT
	DECLARE @ACC_SEASON_ID INT
	DECLARE @ACC_SCHOOL_ID INT
	DECLARE @HEISMAN_YEAR DATE
	SELECT @loopend = COUNT(*) FROM HEISMAN_WINNER
	WHILE @loop <= @loopend
	BEGIN
		SELECT 
			@ACC_SEASON_ID = ACCSEA.ACC_SEASON_ID,
			@ACC_SCHOOL_ID = ACCSEA.ACC_SCHOOL_ID,
			@HEISMAN_YEAR = HWIN.HEISMAN_YEAR
		FROM 
			ACC_SEASON ACCSEA
		INNER JOIN
			HEISMAN_WINNER HWIN
				ON ACCSEA.ACC_SCHOOL_ID = HWIN.ACC_SCHOOL_ID
				AND ACCSEA.SEASON_YEAR = HWIN.HEISMAN_YEAR
				AND HWIN.ACC_SEASON_ID IS NULL
		UPDATE HEISMAN_WINNER SET ACC_SEASON_ID = @ACC_SEASON_ID WHERE ACC_SCHOOL_ID = @ACC_SCHOOL_ID AND HEISMAN_YEAR = @HEISMAN_YEAR
		SELECT @loop = @loop + 1
	END
END
GO

--Implementing the procedure HEISMAN_WINNER_ACC_SEASON_ID
EXEC HEISMAN_WINNER_ACC_SEASON_ID

--Checking the results
SELECT * FROM HEISMAN_WINNER

--Creating a view for ACC Seasons to make them more reasonable
GO
CREATE OR ALTER VIEW ACC_SEASONS_VIEW AS
SELECT
	YEAR(SEASON.SEASON_YEAR) Season,
	SCHOOL.SCHOOL_NAME School,
	SEASON.WINS Wins,
	SEASON.LOSSES Losses,
	SEASON.TIES Ties,
	CAST((SEASON.WINS + (0.5*ISNULL(SEASON.TIES,0))) / (SEASON.WINS + SEASON.LOSSES + ISNULL(SEASON.TIES,0)) AS DECIMAL(4,3)) Win_Percentage,
	CASE SEASON.ACC_CHAMPION WHEN 1 THEN 'ACC Champion' WHEN 0 THEN '' END ACC_Champion_Flag,
	CASE WHEN HEISMAN.HEISMAN_WINNER_ID IS NOT NULL THEN HEISMAN.NAME + ' (' + HEISMAN.POSITION + ')' ELSE '' END Heisman_Flag
FROM
	ACC_SEASON SEASON
LEFT JOIN
	ACC_SCHOOL SCHOOL
		ON SEASON.ACC_SCHOOL_ID = SCHOOL.ACC_SCHOOL_ID
LEFT JOIN
	HEISMAN_WINNER HEISMAN
		ON SEASON.ACC_SEASON_ID = HEISMAN.ACC_SEASON_ID
GO

--Check our results
SELECT * FROM ACC_SEASONS_VIEW


--Creating a view for School Totals
GO
CREATE OR ALTER VIEW ACC_SCHOOLS_VIEW AS
SELECT
	SCHOOL.SCHOOL_NAME School,
	SCHOOL.SCHOOL_CITY City,
	SCHOOL.SCHOOL_STATE State,
	SCHOOL.GRADUATION_RATE Graduation_Rate,
	COUNT(DISTINCT YEAR(SEASON.SEASON_YEAR)) ACC_Seasons,
	SUM(SEASON.WINS) ACC_Wins,
	SUM(SEASON.LOSSES) ACC_Losses,
	SUM(ISNULL(SEASON.TIES,0)) ACC_Ties,
	CAST((SUM(SEASON.WINS) + (0.5*SUM(ISNULL(SEASON.TIES,0)))) / SUM(SEASON.WINS + SEASON.LOSSES + ISNULL(SEASON.TIES,0)) AS DECIMAL(4,3)) ACC_Win_Percentage,
	SUM(CASE SEASON.ACC_CHAMPION WHEN 1 THEN 1 WHEN 0 THEN 0 END) ACC_Championships,
	COUNT(DISTINCT CASE WHEN HEISMAN.ACC_SEASON_ID IS NOT NULL THEN HEISMAN.HEISMAN_WINNER_ID END) ACC_Heisman_Winners,
	COUNT(DISTINCT HEISMAN.HEISMAN_WINNER_ID) Total_Heisman_Trophy_Winners
FROM
	ACC_SCHOOL SCHOOL
LEFT JOIN
	ACC_SEASON SEASON
		ON SCHOOL.ACC_SCHOOL_ID = SEASON.ACC_SCHOOL_ID
LEFT JOIN
	HEISMAN_WINNER HEISMAN
		ON SCHOOL.ACC_SCHOOL_ID = HEISMAN.ACC_SCHOOL_ID
GROUP BY
	SCHOOL.SCHOOL_NAME,
	SCHOOL.SCHOOL_CITY,
	SCHOOL.SCHOOL_STATE,
	SCHOOL.GRADUATION_RATE
GO

--Check the results
SELECT * FROM ACC_SCHOOLS_VIEW


--Creating view for Heisman Winners
GO
CREATE OR ALTER VIEW HEISMAN_VIEW AS
SELECT
	HEISMAN.HEISMAN_YEAR Season,
	HEISMAN.NAME Player,
	HEISMAN.HEISMAN_SCHOOL_NAME School,
	HEISMAN.POSITION Position,
	HEISMAN.CLASS + CASE HEISMAN.REDSHIRT WHEN 1 THEN ' (RS)' WHEN 0 THEN '' END Class,
	CASE WHEN SCHOOL.ACC_SCHOOL_ID IS NOT NULL THEN SCHOOL.SCHOOL_NAME ELSE '' END ACC_School_Flag,
	CASE WHEN SEASON.ACC_SEASON_ID IS NOT NULL THEN 'ACC' ELSE '' END ACC_Season_Flag,
	SEASON.WINS ACC_Wins,
	SEASON.LOSSES ACC_Losses,
	SEASON.TIES ACC_Ties,
	CAST((SEASON.WINS + (0.5*ISNULL(SEASON.TIES,0))) / (SEASON.WINS + SEASON.LOSSES + ISNULL(SEASON.TIES,0)) AS DECIMAL(4,3)) ACC_Win_Percentage,
	CASE SEASON.ACC_CHAMPION WHEN 1 THEN 'ACC Champion' ELSE '' END ACC_Champion_Flag
FROM
	HEISMAN_WINNER HEISMAN
LEFT JOIN
	ACC_SCHOOL SCHOOL
		ON HEISMAN.ACC_SCHOOL_ID = SCHOOL.ACC_SCHOOL_ID
LEFT JOIN
	ACC_SEASON SEASON
		ON HEISMAN.ACC_SEASON_ID = SEASON.ACC_SEASON_ID
GO


--Check the results
SELECT * FROM HEISMAN_VIEW



--Creating stored procedure in order to enter data for Heisman Winners
GO
CREATE OR ALTER PROCEDURE ENTER_HEISMAN
(@HEISMAN_YEAR DATE,@NAME VARCHAR(50),@HEISMAN_SCHOOL_NAME VARCHAR(50),@POSITION VARCHAR(10),@CLASS VARCHAR(10),@REDSHIRT BIT) AS
BEGIN
	INSERT INTO HEISMAN_WINNER (HEISMAN_YEAR,NAME,HEISMAN_SCHOOL_NAME,POSITION,CLASS,REDSHIRT)
		VALUES (@HEISMAN_YEAR,@NAME,@HEISMAN_SCHOOL_NAME,@POSITION,@CLASS,@REDSHIRT)
	EXEC HEISMAN_WINNER_ACC_SCHOOL_ID
	EXEC HEISMAN_WINNER_ACC_SEASON_ID 
END
GO

--Testing out
EXEC ENTER_HEISMAN '2021','Nick Videtti','Syracuse University','Waterboy','Graduate',0
SELECT * FROM HEISMAN_VIEW WHERE Player = 'Nick Videtti'

--Removing
DELETE HEISMAN_WINNER WHERE NAME = 'Nick Videtti'
SELECT * FROM HEISMAN_VIEW WHERE Player = 'Nick Videtti'

--Creating stored procedure in order to enter data for seasons
GO
CREATE OR ALTER PROCEDURE ENTER_SEASON
(@SCHOOL_NAME VARCHAR(50),@SEASON_YEAR DATE,@WINS INT,@LOSSES INT,@TIES INT,@ACC_CHAMPION BIT,
@NEW_SCHOOL_CITY VARCHAR(50) = NULL,@NEW_SCHOOL_STATE VARCHAR(2) = NULL,@NEW_GRADUATION_RATE DECIMAL(4,3) = NULL) AS
BEGIN
	IF NOT EXISTS (SELECT * FROM ACC_SCHOOL WHERE SCHOOL_NAME = @SCHOOL_NAME)
	BEGIN
		INSERT INTO ACC_SCHOOL (SCHOOL_NAME, SCHOOL_CITY, SCHOOL_STATE, GRADUATION_RATE)
			VALUES (@SCHOOL_NAME,@NEW_SCHOOL_CITY,@NEW_SCHOOL_STATE,@NEW_GRADUATION_RATE)
	END
	INSERT INTO ACC_SEASON (ACC_SCHOOL_ID,SEASON_YEAR,WINS,LOSSES,TIES,ACC_CHAMPION)
		VALUES ((SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = @SCHOOL_NAME),@SEASON_YEAR,@WINS,@LOSSES,@TIES,@ACC_CHAMPION)
	EXEC HEISMAN_WINNER_ACC_SCHOOL_ID
	EXEC HEISMAN_WINNER_ACC_SEASON_ID
END
GO

--Testing out
EXEC ENTER_SEASON 'St John Fisher College','2040',103,2,765,1,'Rochester','NY',0.934
SELECT * FROM ACC_SEASONS_VIEW WHERE School = 'St John Fisher College' AND Season = '2040'
SELECT * FROM ACC_SCHOOLS_VIEW WHERE School = 'St John Fisher College'

--Removing
DELETE ACC_SEASON WHERE ACC_SCHOOL_ID = (SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'St John Fisher College') AND SEASON_YEAR = '2040'
DELETE ACC_SCHOOL WHERE SCHOOL_NAME = 'St John Fisher College'
SELECT * FROM ACC_SEASONS_VIEW WHERE School = 'St John Fisher College' AND Season = '2040'
SELECT * FROM ACC_SCHOOLS_VIEW WHERE School = 'St John Fisher College'


--Testing out one more time
EXEC ENTER_SEASON 'Syracuse University','1452',1,5,3,0
SELECT * FROM ACC_SEASONS_VIEW WHERE School = 'Syracuse University' AND Season = '1452'
SELECT * FROM ACC_SCHOOLS_VIEW WHERE School = 'Syracuse University'

--Removing one more time
DELETE ACC_SEASON WHERE ACC_SCHOOL_ID = (SELECT ACC_SCHOOL_ID FROM ACC_SCHOOL WHERE SCHOOL_NAME = 'Syracuse University') AND SEASON_YEAR = '1452'
SELECT * FROM ACC_SEASONS_VIEW WHERE School = 'Syracuse University' AND Season = '1452'

--HYPOTHETICAL ROLES (WILL LEAVE THIS CODE OUT FOR DATA SECUIRTY REASONS AND LACK OF ACCESS ON THE REMOTE LAB)

--CREATE USER ADMIN FOR LOGIN ADMIN
--GRANT SELECT ON ACC_SCHOOL TO ADMIN
--GRANT SELECT ON ACC_SEASON TO ADMIN
--GRANT SELECT ON HEISMAN_WINNER TO ADMIN
--GRANT SELECT ON ACC_SCHOOLS_VIEW TO ADMIN
--GRANT SELECT ON ACC_SEASONS_VIEW TO ADMIN
--GRANT SELECT ON HEISMAN_VIEW TO ADMIN
--GRANT EXECUTE ON ENTER_HEISMAN TO ADMIN
--GRANT EXECUTE ON ENTER_SEASON TO ADMIN
--GRANT EXECUTE ON HEISMAN_WINNER_ACC_SCHOOL_ID TO ADMIN
--GRANT EXECUTE ON HEISMAN_WINNER_ACC_SEASON_ID TO ADMIN

--CREATE USER ANALYST FOR LOGIN ANALYST
--GRANT SELECT ON ACC_SCHOOL TO ADMIN
--GRANT SELECT ON ACC_SEASON TO ADMIN
--GRANT SELECT ON HEISMAN_WINNER TO ADMIN
--GRANT SELECT ON ACC_SCHOOLS_VIEW TO ADMIN
--GRANT SELECT ON ACC_SEASONS_VIEW TO ADMIN
--GRANT SELECT ON HEISMAN_VIEW TO ADMIN

--CREATE USER QUERY FOR LOGIN QUERY
--GRANT SELECT ON ACC_SCHOOLS_VIEW TO ADMIN
--GRANT SELECT ON ACC_SEASONS_VIEW TO ADMIN
--GRANT SELECT ON HEISMAN_VIEW TO ADMIN



-------------------------Answering data questions------------------------------------
--What school has had the most wins in ACC history?
SELECT 
	*
FROM
	ACC_SCHOOLS_VIEW
WHERE
	ACC_Wins = (SELECT MAX(ACC_Wins) FROM ACC_SCHOOLS_VIEW)


--What school has had the most Heisman trophies won by an ACC player?
SELECT * FROM ACC_SCHOOLS_VIEW WHERE ACC_Heisman_Winners = (SELECT MAX(ACC_Heisman_Winners) FROM ACC_SCHOOLS_VIEW)
SELECT * FROM ACC_SCHOOLS_VIEW WHERE Total_Heisman_Trophy_Winners = (SELECT MAX(Total_Heisman_Trophy_Winners) FROM ACC_SCHOOLS_VIEW)


--Assuming a given student-athlete is from West Virginia, Which schools are in West Virginia or in a state bordering West Virginia?
--(West Virginia, Maryland, Virginia, Kentucky, Ohio, or Pennsylvania)
SELECT
	*
FROM
	ACC_SCHOOLS_VIEW
WHERE
	State IN ('WV','MD','VA','KY','OH','PA')

--What school has had the most undefeated (0 loss) seasons?
SELECT
	School,
	COUNT(CASE WHEN Losses = 0 THEN 1 END) Undefeated_Seasons
FROM
	ACC_SEASONS_VIEW
GROUP BY
	School
HAVING
	COUNT(CASE WHEN Losses = 0 THEN 1 END) = (SELECT TOP 1 COUNT(CASE WHEN Losses = 0 THEN 1 END) Undefeated_Seasons
													FROM ACC_SEASONS_VIEW GROUP BY School ORDER BY Undefeated_Seasons DESC)

--Are there any schools in the top 5 for all three of the following metrics?
	--ACC Championships
	--Heisman trophies won by an ACC player
	--Graduation rate

--TOP 5 ACC_Championships
SELECT TOP 5 ACC_Championships FROM (SELECT DISTINCT ACC_Championships FROM ACC_SCHOOLS_VIEW)SUBQUERY ORDER BY ACC_Championships DESC

--TOP 5 ACC_Heisman_Winners
SELECT TOP 5 ACC_Heisman_Winners FROM (SELECT DISTINCT ACC_Heisman_Winners FROM ACC_SCHOOLS_VIEW)SUBQUERY ORDER BY ACC_Heisman_Winners DESC

--TOP 5 Graduation_Rate
SELECT TOP 5 Graduation_Rate FROM (SELECT DISTINCT Graduation_Rate FROM ACC_SCHOOLS_VIEW)SUBQUERY ORDER BY Graduation_Rate DESC

--Putting it all together
SELECT
	*
FROM
	ACC_SCHOOLS_VIEW
WHERE
	ACC_Championships IN
		(SELECT TOP 5 ACC_Championships FROM (SELECT DISTINCT ACC_Championships FROM ACC_SCHOOLS_VIEW)SUBQUERY ORDER BY ACC_Championships DESC)
	AND ACC_Heisman_Winners IN
		(SELECT TOP 5 ACC_Heisman_Winners FROM (SELECT DISTINCT ACC_Heisman_Winners FROM ACC_SCHOOLS_VIEW)SUBQUERY ORDER BY ACC_Heisman_Winners DESC)
	AND Graduation_Rate IN
		(SELECT TOP 5 Graduation_Rate FROM (SELECT DISTINCT Graduation_Rate FROM ACC_SCHOOLS_VIEW)SUBQUERY ORDER BY Graduation_Rate DESC)